// File generated by FlutterFire CLI.
// This is a placeholder - you'll need to run: flutterfire configure
// to generate the actual configuration for your Firebase project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC485kp1_-rDQJ2NjfICit0UZV3WN0N5ks',
    appId: '1:772312603292:web:ef8ad91cbf24ee9e5aeb59',
    messagingSenderId: '772312603292',
    projectId: 'shopie-d0230',
    authDomain: 'shopie-d0230.firebaseapp.com',
    storageBucket: 'shopie-d0230.firebasestorage.app',
    measurementId: 'G-R7ECRL797X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC485kp1_-rDQJ2NjfICit0UZV3WN0N5ks',
    appId: '1:772312603292:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '772312603292',
    projectId: 'shopie-d0230',
    storageBucket: 'shopie-d0230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC485kp1_-rDQJ2NjfICit0UZV3WN0N5ks',
    appId: '1:772312603292:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '772312603292',
    projectId: 'shopie-d0230',
    storageBucket: 'shopie-d0230.firebasestorage.app',
    iosBundleId: 'com.example.shopie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC485kp1_-rDQJ2NjfICit0UZV3WN0N5ks',
    appId: '1:772312603292:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '772312603292',
    projectId: 'shopie-d0230',
    storageBucket: 'shopie-d0230.firebasestorage.app',
    iosBundleId: 'com.example.shopie',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC485kp1_-rDQJ2NjfICit0UZV3WN0N5ks',
    appId: '1:772312603292:web:ef8ad91cbf24ee9e5aeb59',
    messagingSenderId: '772312603292',
    projectId: 'shopie-d0230',
    authDomain: 'shopie-d0230.firebaseapp.com',
    storageBucket: 'shopie-d0230.firebasestorage.app',
    measurementId: 'G-R7ECRL797X',
  );
}
